const Products = [
    { category: "milk", type: "milk", searchName: "token milk", productName: "Token Milk", quantity: "500ml", price: 22 },
    { category: "milk", type: "milk", searchName: "token milk", productName: "Token Milk", quantity: "1L", price: 40 },
    { category: "milk", type: "milk", searchName: "ultra milk", productName: "Ultra Milk", quantity: "500ml", price: 25 },
    { category: "milk", type: "milk", searchName: "ultra milk", productName: "Ultra Milk", quantity: "1L", price: 48 },
    { category: "milk", type: "milk", searchName: "full cream milk", productName: "Full Cream Milk", quantity: "500ml", price: 28 },
    { category: "milk", type: "milk", searchName: "full cream milk", productName: "Full Cream Milk", quantity: "1L", price: 54 },
    { category: "milk", type: "milk", searchName: "toned milk", productName: "Toned Milk", quantity: "500ml", price: 22 },
    { category: "milk", type: "milk", searchName: "toned milk", productName: "Toned Milk", quantity: "1L", price: 40 },
    { category: "milk", type: "milk", searchName: "standardized milk", productName: "Standardized Milk", quantity: "500ml", price: 24 },
    { category: "milk", type: "milk", searchName: "standardized milk", productName: "Standardized Milk", quantity: "1L", price: 45 },
    { category: "milk", type: "milk", searchName: "cow milk", productName: "Cow Milk", quantity: "500ml", price: 23 },
    { category: "milk", type: "milk", searchName: "cow milk", productName: "Cow Milk", quantity: "1L", price: 45 },
    { category: "milk", type: "milk", searchName: "super - t milk", productName: "Super - T Milk", quantity: "500ml", price: 24 },
    { category: "milk", type: "milk", searchName: "super - t milk", productName: "Super - T Milk", quantity: "1L", price: 47 },
    { category: "milk", type: "milk", searchName: "dietz milk", productName: "Dietz Milk", quantity: "500ml", price: 28 },
    { category: "milk", type: "milk", searchName: "dietz milk", productName: "Dietz Milk", quantity: "1L", price: 55 },
    { category: "milk", type: "milk", searchName: "live lite milk", productName: "Live Lite Milk", quantity: "500ml", price: 19 },
    { category: "milk", type: "milk", searchName: "live lite milk", productName: "Live Lite Milk", quantity: "1L", price: 36 },
    { category: "milk", type: "milk", searchName: "fullYo milk", productName: "FullYo Milk", quantity: "500ml", price: 27 },
    { category: "milk", type: "milk", searchName: "fullYo milk", productName: "FullYo Milk", quantity: "1L", price: 53 },
    { category: "curd", type: "curd", searchName: "ultimate dahi", productName: "Ultimate Dahi", quantity: "200gm", price: 30 },
    { category: "curd", type: "curd", searchName: "nurtifit probiotic dahi", productName: "Nurtifit Probiotic Dahi", quantity: "200gm", price: 25 },
    { category: "curd", type: "curd", searchName: "classic dahi", productName: "Classic Dahi", quantity: "200gm", price: 20 },
    { category: "curd", type: "curd", searchName: "dahi", productName: "Dahi", quantity: "1Kg", price: 60 },
    { category: "curd", type: "curd", searchName: "dahi cup", productName: "Dahi Cup", quantity: "2Kg", price: 190 },
    { category: "curd", type: "curd", searchName: "dahi cup", productName: "Dahi Cup", quantity: "5Kg", price: 360 },
    { category: "curd", type: "curd", searchName: "misthi doi", productName: "Misthi Doi", quantity: "90ml", price: 15 },
    { category: "curd", type: "curd", searchName: "aam doi", productName: "Aam Doi", quantity: "85gm", price: 15 },
    { category: "chach", type: "chach", searchName: "normal chach", productName: "Normal Chach", quantity: "200ml", price: 10 },
    { category: "chach", type: "chach", searchName: "masala chach", productName: "Masala Chach", quantity: "200ml", price: 10 },
    { category: "paneer", type: "paneer", searchName: "paneer", productName: "Paneer", quantity: "200gm", price: 70 },
    { category: "paneer", type: "paneer", searchName: "paneer", productName: "Paneer", quantity: "500gm", price: 180 },
    { category: "paneer", type: "paneer", searchName: "paneer", productName: "Paneer", quantity: "1Kg", price: 320 },
    { category: "butter", type: "butter", searchName: "butter", productName: "Butter", quantity: "500gm", price: 210 },
    { category: "cheese", type: "cheese", searchName: "cheese slice", productName: "Cheese Slice", quantity: "200gm", price: 130 },
    { category: "cheese", type: "cheese", searchName: "cheese cubes", productName: "Cheese Cubes", quantity: "180gm", price: 110 },
    { category: "cheese", type: "cheese", searchName: "cheese spread", productName: "Cheese Spread", quantity: "200gm", price: 100 },
    { category: "cheese", type: "cheese", searchName: "cheese block", productName: "Cheese Block", quantity: "200gm", price: 150 },
    { category: "sweet", type: "sweet", searchName: "gulab jamun", productName: "Gulab Jamun", quantity: "2pc.", price: 50 },
    { category: "sweet", type: "sweet", searchName: "gulab jamun", productName: "Gulab Jamun", quantity: "1Kg", price: 220 },
    { category: "sweet", type: "sweet", searchName: "rasgulla", productName: "Rasgulla", quantity: "2pc.", price: 40 },
    { category: "sweet", type: "sweet", searchName: "rasgulla", productName: "Rasgulla", quantity: "1Kg", price: 210 },
    { category: "sweet", type: "sweet", searchName: "milk cake", productName: "Milk Cake", quantity: "400gm", price: 220 },
    { category: "sweet", type: "sweet", searchName: "rasmalai", productName: "Rasmalai", quantity: "500gm", price: 220 },
    { category: "sweet", type: "sweet", searchName: "orange mawa barfi", productName: "Orange Mawa Barfi", quantity: "400gm", price: 220 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "vanilla", productName: "Vanilla", quantity: "700ml", price: 180 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "rabri kulfi", productName: "Rabri kulfi", quantity: "700ml", price: 240 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "strawberry", productName: "Strawberry", quantity: "700ml", price: 200 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "mango magic", productName: "Mango Magic", quantity: "700ml", price: 220 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "choco chip", productName: "Choco chip", quantity: "1.25L", price: 230 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "butterscotch", productName: "Butterscotch", quantity: "700ml", price: 220 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "chocolate", productName: "Chocolate", quantity: "700ml", price: 220 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "fruit & nut", productName: "Fruit & Nut", quantity: "700ml", price: 250 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "choco fudge", productName: "Choco Fudge", quantity: "700ml", price: 240 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "tutti fruiti", productName: "Tutti fruiti", quantity: "700ml", price: 220 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "two in one", productName: "Two in One", quantity: "700ml", price: 190 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "american nutty delight", productName: "American Nutty Delight", quantity: "700ml", price: 250 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "shahi tukda", productName: "Shahi Tukda", quantity: "700ml", price: 280 },
    { category: "ice cream", type: "bricks and super saver packs", searchName: "cookie & cream", productName: "Cookie & Cream", quantity: "700ml", price: 210 },
    { category: "ice cream", type: "bar", searchName: "choco bar", productName: "Choco Bar", quantity: "65ml", price: 10 },
    { category: "ice cream", type: "bar", searchName: "choco treat", productName: "Choco Treat", quantity: "65ml", price: 20 },
    { category: "ice cream", type: "bar", searchName: "mango bar", productName: "Mango Bar", quantity: "65ml", price: 10 },
    { category: "ice cream", type: "bar", searchName: "choco orange", productName: "Choco Orange", quantity: "65ml", price: 10 },
    { category: "ice cream", type: "bar", searchName: "chillz chocolate premium bar", productName: "Chillz Chocolate Premium Bar", quantity: "65ml", price: 30 },
    { category: "ice cream", type: "bar", searchName: "chillz almond premium bar", productName: "Chillz Almond Premium Bar", quantity: "65ml", price: 35 },
    { category: "ice cream", type: "bar", searchName: "choco crunch bar", productName: "Choco Crunch Bar", quantity: "65ml", price: 25 },
    { category: "ice cream", type: "bar", searchName: "chillz choco mini bar", productName: "Chillz Choco Mini Bar", quantity: "65ml", price: 20 },
    { category: "ice cream", type: "bar", searchName: "chillz atrangi bar", productName: "Chillz Atrangi Bar", quantity: "65ml", price: 20 },
    { category: "ice cream", type: "bar", searchName: "chillz choco sparkel", productName: "Chillz Choco Sparkel", quantity: "65ml", price: 40 },
    { category: "ice cream", type: "cone", searchName: "choco bliss cone", productName: "Choco Bliss Cone", quantity: "100ml", price: 35 },
    { category: "ice cream", type: "cone", searchName: "choco vanilla cone", productName: "Choco Vanilla Cone", quantity: "100ml", price: 25 },
    { category: "ice cream", type: "cone", searchName: "butter scotch cone", productName: "Butter Scotch Cone", quantity: "100ml", price: 30 },
    { category: "ice cream", type: "cone", searchName: "choconado cone", productName: "Choconado Cone", quantity: "100ml", price: 40 },
    { category: "ice cream", type: "cone", searchName: "chillz cookie n crunch cone", productName: "Chillz Cookie n Crunch Cone", quantity: "100ml", price: 35 },
    { category: "ice cream", type: "kulfi", searchName: "pista kulfi", productName: "Pista kulfi", quantity: "60ml", price: 30 },
    { category: "ice cream", type: "kulfi", searchName: "kesar kamaal kulfi", productName: "Kesar Kamaal kulfi", quantity: "60ml", price: 20 },
    { category: "ice cream", type: "kulfi", searchName: "rose kulfi", productName: "Rose kulfi", quantity: "60ml", price: 25 },
    { category: "ice cream", type: "kulfi", searchName: "rabri kulfi", productName: "Rabri kulfi", quantity: "60ml", price: 25 },
    { category: "ice cream", type: "kulfi", searchName: "matka kulfi", productName: "Matka kulfi", quantity: "60ml", price: 40 },
    { category: "ice cream", type: "kulfi", searchName: "rajwadi kulfi", productName: "Rajwadi kulfi", quantity: "60ml", price: 30 },

];

exports.Products = Products;